## mk-get-fst-per-gene
## Define shell command line which will be used to run scripts.
MKSHELL="/bin/bash"

%.weir.fst:Q: %.vcf.gz $REF_GENE $POP_OUTGROUP $POP_INGROUP %.chbvsmxl.weir.fst %.pelvsmxl.weir.fst
	echo "[DEBUG] Calculating Fst for $POP_INGROUP and $POP_OUTGROUP"
	chromosome=$(bcftools view -H "$stem".vcf | cut -f1 | uniq )
	awk -v ch=$chromosome '$1==ch {print $0}' $REF_GENE > ref_gene
	while read line
	do
		echo "[DEBUG] working in line: $line"
		start=$(echo "$line" | cut -f3)
		end=$(echo "$line" | cut -f4)
		chromosome=$(echo "$line" | cut -f1)
		segment=$(echo "$line" | cut -f5)
		if [[ "$stem" == .*_chrom"$chromosome" ]] ; then
			vcftools --vcf $stem.vcf \
				 --weir-fst-pop $POP_OUTGROUP \
				 --weir-fst-pop $POP_INGROUP \
				 --out $segment.$POP_3 --chr $chromosome \
				 --from-bp $start --to-bp $end 2>&1 | tee > "$segment"."$POP_3".log
		fi
	done < ref_gene \
	&& bgzip --threads 10 $stem.vcf \
	&& rm ref_gene

%.chbvsmxl.weir.fst:Q: %.vcf.gz $REF_GENE $POP_OUTGROUP %.pelvsmxl.weir.fst
	echo "[DEBUG] Calculating Fst for $POP_TARGET and $POP_OUTGROUP"
	chromosome=$(bcftools view -H "$stem".vcf | cut -f1 | uniq )
	awk -v ch=$chromosome '$1==ch {print $0}' $REF_GENE > ref_gene
	while read line
	do
		echo "[DEBUG] working in line: $line"
		start=$(echo "$line" | cut -f3)
		end=$(echo "$line" | cut -f4)
		chromosome=$(echo "$line" | cut -f1)
		segment=$(echo "$line" | cut -f5)
		if [[ "$stem" == .*_chrom"$chromosome" ]] ; then
			vcftools --vcf $stem.vcf \
			 	--weir-fst-pop $POP_OUTGROUP \
			 	--weir-fst-pop $POP_TARGET \
			 	--out $segment.$POP_1 --chr $chromosome \
			 	--from-bp $start --to-bp $end 2>&1 | tee > "$segment"."$POP_1".log
		fi
	done < ref_gene \
	&& rm ref_gene

%.pelvsmxl.weir.fst:Q: %.vcf.gz $REF_GENE $POP_INGROUP
	echo "[DEBUG] Calculating Fst for $POP_TARGET and $POP_INGROUP"
	chromosome=$(bcftools view -H "$stem".vcf.gz | cut -f1 | uniq )
	awk -v ch=$chromosome '$1==ch {print $0}' $REF_GENE > ref_gene
	bgzip -d --threads 10 $stem.vcf.gz \
	&& while read line
	do
		echo "[DEBUG] working in line: $line"
		start=$(echo "$line" | cut -f3)
		end=$(echo "$line" | cut -f4)
		chromosome=$(echo "$line" | cut -f1)
		segment=$(echo "$line" | cut -f5)
		if [[ "$stem" == .*_chrom"$chromosome" ]] ; then
			vcftools --vcf $stem.vcf \
			 	--weir-fst-pop $POP_INGROUP \
			 	--weir-fst-pop $POP_TARGET \
			 	--out $segment.$POP_2 --chr $chromosome \
			 	--from-bp $start --to-bp $end 2>&1 | tee > "$segment"."$POP_2".log
		fi
	done < ref_gene \
	&& rm ref_gene
