## mk-get-fst-per-gene
## Define shell command line which will be used to run scripts.
MKSHELL="/bin/bash"

%.weir.fst: %.vcf.gz $REF_GENE $POP_OUTGROUP $POP_INGROUP %.chbvsmxl.weir.fst %.pelvsmxl.weir.fst
	echo "[DEBUG] Calculating Fst for $POP_INGROUP and $POP_OUTGROUP"
	while read line
	do
		echo "[DEBUG] working in line: $line"
		start=$(echo "$line" | cut -f3)
		end=$(echo "$line" | cut -f4)
		chromosome=$(echo "$line" | cut -f1)
		segment=$(echo "$line" | cut -f5)
		vcftools --vcf $stem.vcf \
			 --weir-fst-pop $POP_OUTGROUP \
			 --weir-fst-pop $POP_INGROUP \
			 --out $segment.$POP_3 --chr $chromosome \
			 --from-bp $start --to-bp $end 2>&1 | tee > $segment.$POP_3.log
	done < $REF_GENE  \
	&& bgzip $stem.vcf

%.chbvsmxl.weir.fst: %.vcf.gz $REF_GENE $POP_OUTGROUP %.pelvsmxl.weir.fst
	echo "[DEBUG] Calculating Fst for $POP_TARGET and $POP_OUTGROUP"
	while read line
	do
		echo "[DEBUG] working in line: $line"
		start=$(echo "$line" | cut -f3)
		end=$(echo "$line" | cut -f4)
		chromosome=$(echo "$line" | cut -f1)
		segment=$(echo "$line" | cut -f5)
		vcftools --vcf $stem.vcf \
			 --weir-fst-pop $POP_OUTGROUP \
			 --weir-fst-pop $POP_TARGET \
			 --out $segment.$POP_1 --chr $chromosome \
			 --from-bp $start --to-bp $end 2>&1 | tee > $segment.$POP_1.log
	done < $REF_GENE

%.pelvsmxl.weir.fst:Q: %.vcf.gz $REF_GENE $POP_INGROUP
	echo "[DEBUG] Calculating Fst for $POP_TARGET and $POP_INGROUP"
	bgzip -d $stem.vcf.gz \
	&& while read line
	do
		echo "[DEBUG] working in line: $line"
		start=$(echo "$line" | cut -f3)
		end=$(echo "$line" | cut -f4)
		chromosome=$(echo "$line" | cut -f1)
		segment=$(echo "$line" | cut -f5)
		vcftools --vcf $stem.vcf \
			 --weir-fst-pop $POP_INGROUP \
			 --weir-fst-pop $POP_TARGET \
			 --out $segment.$POP_2 --chr $chromosome \
			 --from-bp $start --to-bp $end 2>&1 | tee > $segment.$POP_2.log
	done < $REF_GENE 
