### mk-get-GeneHancer-variants ###
# mkfile script with dependency rules for:
#	1. To separate variants with a GeneHancer ID. For more information about GeneHancer, see https://genome.ucsc.edu/cgi-bin/hgTrackUi?db=hg19&g=geneHancer
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.SEPARATE_LNCRNA_PROMOTERS:QV: %.lncRNA_promoters.vcf
	echo "[DEBUG] Done separating variants by lncRNA_promoter affected"

## Filter vep is a VEP tool described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html
# -i, input file
# -o, output file
# --vcf_info_field, VEP finds annotations in ANN field
# -filter, VEP finds variants where it matches with "lncRNA_promoter"
# --force_overwrite, forces an ouput file
%.lncRNA_promoters.vcf:Q: %.vcf
	echo "[DEBUG] extracting lncRNA_promoter variants for $prereq"
	filter_vep \
		-i $prereq \
		-o $target.build \
		--vcf_info_field ANN \
		-filter "lncRNA_promoter" \
		--force_overwrite \
	&& mv $target.build $target
