## mk-wrangling-per-gene
## Define shell command line which will be used to run scripts.
MKSHELL="/bin/bash"

%.csv:QV:
	dir=$(dirname $target)
	filename=$(echo $target | sed 's#.csv##' | xargs -n 1 basename)
	#echo "$filename"
	#echo $dir
	echo "[DEBUG] wrangling data for $filename "
	#ls test/data/*AC066595.1.mx_pel.weir.fst | sed "s#[a-z].*_chrom[0-9]*.##" | sort -u
	Rscript --vanilla wrangling.R $dir/ $filename
