### mk-run-ihs-xpehh ###
# mkfile script with dependency rules for:
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.ihs.tsv:Q: %.vcf.gz
	echo "[DEBUG] Running iHS for $prereq"
	number_lines=$(bcftools view -H "$prereq" | wc -l)
	if [[ $number_lines > 0 ]]
	then
	end_file=".vcf.gz"
	#echo "$prereq $target"
	bcftools view -H $prereq | cut -f 1,2,3 > $stem.rsid
	Rscript --vanilla mxb_selection_ihs.R $prereq $target $THREADS $stem".rsid" \
	&& rm $stem.rsid
	else
	touch $target
	fi
