## mk-calculate-pbs-per-gene
## Define shell command line which will be used to run scripts.
MKSHELL="/bin/bash"

%/snp_pbs_results.tsv:Q: %/
	echo "[DEBUG] Calculating PBS per gene for $(ls $prereq*.csv)"
	#echo "$( ls $prereq/*{1..22}.$POP_1.weir.fst )"
	awk 'FNR>1 || NR==1' $prereq/*{1..22}.$POP_1.weir.fst > $prereq/$POP_1
	awk 'FNR>1 || NR==1' $prereq/*{1..22}.$POP_2.weir.fst > $prereq/$POP_2
	awk 'FNR>1 || NR==1' $prereq/*{1..22}.$POP_3.weir.fst > $prereq/$POP_3
	rm $prereq/*.fst
	mv $prereq/$POP_1 $prereq/$POP_1.weir.fst
	mv $prereq/$POP_2 $prereq/$POP_2.weir.fst
	mv $prereq/$POP_3 $prereq/$POP_3.weir.fst
	Rscript --vanilla pbs_calculator.R $prereq $target $POP_1 $POP_2 $POP_3
