### mk-run-ihs-xpehh ###
# mkfile script with dependency rules for:
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.png:Q: %.csv
	echo "[DEBUG] Plotting iHS results for $prereq"
	Rscript --vanilla plot_ihs.R $prereq $target
