### mk-run-ihs-xpehh ###
# mkfile script with dependency rules for:
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.xpehh.tsv:Q: %.vcf.gz
	number_lines=$(bcftools view -H "$prereq" | wc -l)
	if [[ $number_lines > 0 ]]
	then
	end_file=".vcf.gz"
	chromosome=$(basename "$prereq" "$end_file" | sed "s#[a-z]*.*_chrom##")
	echo "[DEBUG] Running XP-EHH for chromosome $chromosome"
	#echo "$chromosome $stem $end_file $FIRST_POP $SECOND_POP $target $STEM_INGROUP $END_FILE_INGROUP"
	Rscript --vanilla mxb_selection_xp-ehh.R $chromosome $stem $end_file $FIRST_POP $SECOND_POP $target $STEM_INGROUP $END_FILE_INGROUP
	else
	touch $target
	fi
	# && rm $stem.chrom
