### mk-run-ihs-xpehh ###
# mkfile script with dependency rules for:
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.xpehh.tsv:Q: %.vcf.gz
	echo "[DEBUG] Running XP-EHH for $prereq"
	number_lines=$(bcftools view -H "$prereq" | wc -l)
	if [[ $number_lines > 0 ]]
	then
	end_file=".vcf.gz"
	chromosome=$(basename "$prereq" "$end_file" | sed "s#[a-z]*.*_chrom##")
	bcftools view -H $prereq | cut -f 1,2,3 > $stem.rsid
	echo "$chromosome $prereq $FIRST_POP $SECOND_POP $target $STEM_INGROUP $END_FILE_INGROUP $THREADS"
	Rscript --vanilla mxb_selection_xp-ehh.R $chromosome $prereq $FIRST_POP $SECOND_POP $target $STEM_INGROUP $END_FILE_INGROUP $THREADS $stem".rsid" \
	&& rm $stem.rsid
	else
		touch $target
	fi
